"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";

import { liveGet, livePost } from "@/lib/live-api";
import { formatRecoveryCycle, nextRecoveryCycle } from "@/lib/recovery-schedule";

type Entry = { at: string; speaker?: string; headline?: string; body?: string; summary?: string; provenance?: string; kind?: string };
type Payment = { id: string; amount_display: string; method_label?: string; reference: string; received_on: string; reversed_at?: string | null };
type Detail = {
  id: string; invoice_number: string; customer_name: string; customer_email: string; amount_display: string; paid_display: string; outstanding_display: string; link_paid_display: string; external_paid_display: string; refunded_display: string; chargeback_display: string; provider_net_display: string; status: string; days_overdue: number; due_at: string; why: string; why_next: string; payment_url?: string | null; payment_link_status?: string | null; conversation: Entry[]; timeline: Entry[]; external_payments: Payment[]; reminders: { tier: number; tone: string; subject: string; body: string; generated_by: string }[]; promises: { id: string; promised_date: string; amount_display: string; status: string; excerpt: string; confidence: number }[]; dispute?: { id: string; reason: string; summary: string; confidence_display: string; source_excerpt: string; next_action: string } | null;
};

export default function LiveInvoiceDetailPage() {
  const params = useParams<{ id: string }>();
  const [merchant, setMerchant] = useState("");
  const [data, setData] = useState<Detail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const load = (id: string) => liveGet<Detail>(`/api/live/workspace/invoices/${params.id}`, id).then(setData);
  useEffect(() => { const id = window.localStorage.getItem("vasooli_live_merchant") || ""; Promise.resolve().then(() => { setMerchant(id); if (id) liveGet<Detail>(`/api/live/workspace/invoices/${params.id}`, id).then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load invoice")); }); }, [params.id]);

  async function recordPayment(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setError(null);
    try { await livePost(`/api/live/workspace/invoices/${params.id}/payments`, merchant, { amount_paise: Math.round(Number(form.get("amount")) * 100), method: form.get("method"), reference: form.get("reference"), received_on: form.get("received_on"), note: form.get("note") }); setMessage("Payment recorded and the recovery balance was recalculated."); await load(merchant); event.currentTarget.reset(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Could not record payment"); }
  }
  async function escalate() { try { await livePost(`/api/live/workspace/invoices/${params.id}/escalate`, merchant); setMessage("Invoice moved to human review."); await load(merchant); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not escalate"); } }
  async function resolve(resume: boolean) { if (!data?.dispute) return; const note = window.prompt(resume ? "Decision note (required to resume recovery)" : "Resolution note", "") ?? ""; if (resume && !note.trim()) return; try { await livePost(`/api/live/workspace/disputes/${data.dispute.id}/resolve`, merchant, { note, resume_recovery: resume }); setMessage(resume ? "Dispute resolved; recovery resumed." : "Dispute resolved; recovery remains stopped."); await load(merchant); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not resolve dispute"); } }

  if (!data) return <div><Link href="/live/invoices" className="text-sm text-accent">← Recovery queue</Link><p className="mt-8 text-sm text-ink-4">{error || "Loading invoice…"}</p></div>;
  return <div className="space-y-6">
    <div><Link href="/live/invoices" className="text-xs text-ink-3 hover:text-ink-2">← Recovery queue</Link><div className="mt-2 flex flex-wrap items-baseline gap-x-4 gap-y-2"><h1 className="font-mono text-xl font-semibold text-ink">{data.invoice_number}</h1><span className="text-ink-2">{data.customer_name}</span><span className="rounded-full border border-line bg-panel px-2.5 py-0.5 text-[11px] font-medium capitalize text-ink-2">{data.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-xs text-ink-4">{data.customer_email} · Due {new Date(data.due_at).toLocaleDateString("en-IN")}</p></div>
    {message ? <p className="mt-4 rounded-xl bg-emerald-500/10 p-4 text-sm text-emerald-700">{message}</p> : null}{error ? <p role="alert" className="mt-4 rounded-xl bg-rose-500/10 p-4 text-sm text-rose-700">{error}</p> : null}
    <section className="rounded-xl border border-line bg-panel px-5 py-4"><p className="text-xs uppercase tracking-wider text-ink-3">Why Vasooli is doing this</p><h2 className="mt-2 text-base font-semibold">{data.why}</h2><p className="mt-1 text-sm text-ink-3">Next: {data.why_next}</p>{/reminder due/i.test(data.why) && !data.dispute ? <div className="mt-4 flex items-start gap-3 rounded-lg border border-accent/25 bg-accent/8 px-3 py-3"><span aria-hidden className="mt-0.5 text-accent">◷</span><div><p className="text-xs font-semibold uppercase tracking-wider text-accent">Scheduled send · {formatRecoveryCycle(nextRecoveryCycle())}</p><p className="mt-1 text-xs font-medium text-ink-2">Recipient: {data.customer_email}</p><p className="mt-1 text-xs leading-5 text-ink-3">Nothing is sent before this recovery cycle. Vasooli checks for payments, disputes, active promises, and policy holds again immediately before sending.</p></div></div> : null}</section>
    {data.dispute ? <section className="rounded-xl border border-amber-500/30 bg-amber-500/5 px-5 py-4"><p className="text-xs font-semibold uppercase tracking-wider text-amber-700">Open dispute · recovery paused</p><h2 className="mt-2 text-base font-semibold">{data.dispute.reason}</h2><p className="mt-2 text-sm text-ink-3">{data.dispute.summary}</p><blockquote className="mt-3 border-l-2 border-amber-500 pl-3 text-sm text-ink-3">{data.dispute.source_excerpt}</blockquote><p className="mt-3 text-xs text-ink-4">{data.dispute.next_action}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => resolve(false)} className="rounded-lg border border-line px-3 py-2 text-sm">Resolve, keep stopped</button><button type="button" onClick={() => resolve(true)} className="rounded-lg bg-accent px-3 py-2 text-sm font-semibold text-white">Resolve and resume</button></div></section> : null}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Amount", data.amount_display], ["Paid", data.paid_display], ["Outstanding", data.outstanding_display], ["Days overdue", `${data.days_overdue}d`]].map(([label, value]) => <div key={label} className="rounded-xl border border-line bg-panel px-5 py-4"><div className="text-xs uppercase tracking-wider text-ink-3">{label}</div><div className="mt-1 text-lg font-semibold tabular-nums">{value}</div></div>)}</section>
    <div className="grid gap-6 lg:grid-cols-[1.15fr_1fr]">
      <div className="space-y-5">
        <div><h2 className="mb-1 text-sm font-semibold">Conversation <span className="ml-2 font-normal text-ink-3">everything said about this invoice, in order</span></h2><p className="mb-3 text-xs text-ink-3">Customer messages, reminders, policy decisions, and payment events.</p><section className="rounded-xl border border-line bg-panel">{data.conversation.length ? <div className="divide-y divide-line">{data.conversation.map((entry, index) => <article key={`${entry.at}-${index}`} className="px-4 py-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{entry.speaker || entry.kind?.replaceAll("_", " ")}</p><time className="text-xs text-ink-4">{new Date(entry.at).toLocaleString("en-IN")}</time></div><p className="mt-1 text-sm">{entry.headline}</p>{entry.body ? <p className="mt-2 whitespace-pre-wrap text-[13px] leading-6 text-ink-3">{entry.body}</p> : null}</article>)}</div> : <p className="p-6 text-center text-sm text-ink-4">No messages yet.</p>}</section></div>
        <div><h2 className="mb-3 text-sm font-semibold">Timeline <span className="ml-2 font-normal text-ink-3">provisioned → chased → reconciled</span></h2><ol className="space-y-1.5">{data.timeline.map((entry, index) => <li key={`${entry.at}-${index}`} className="flex items-start gap-3 rounded-lg border border-line-2 bg-panel px-3 py-2"><span className="min-w-20 text-xs uppercase text-ink-4">{entry.provenance}</span><span className="flex-1 text-sm text-ink-2">{entry.summary}</span><time className="text-xs text-ink-4">{new Date(entry.at).toLocaleString("en-IN")}</time></li>)}</ol></div>
      </div>
      <aside className="space-y-4">
        <section className="rounded-2xl border border-line bg-panel p-5"><h2 className="font-semibold">Payment reconciliation</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-ink-4">Invoice total</dt><dd>{data.amount_display}</dd></div><div className="flex justify-between"><dt className="text-ink-4">Razorpay collected</dt><dd>{data.link_paid_display}</dd></div><div className="flex justify-between"><dt className="text-ink-4">Refunded</dt><dd>-{data.refunded_display}</dd></div><div className="flex justify-between"><dt className="text-ink-4">Chargebacks lost</dt><dd>-{data.chargeback_display}</dd></div><div className="flex justify-between"><dt className="text-ink-4">Provider net</dt><dd>{data.provider_net_display}</dd></div><div className="flex justify-between"><dt className="text-ink-4">Merchant / ERP asserted</dt><dd>{data.external_paid_display}</dd></div><div className="flex justify-between border-t border-line pt-2 font-semibold"><dt>Outstanding</dt><dd>{data.outstanding_display}</dd></div></dl>{data.payment_url ? <a href={data.payment_url} target="_blank" rel="noreferrer" className="mt-4 block rounded-lg border border-line px-3 py-2 text-center text-sm">Open payment link ↗</a> : null}</section>
        <form onSubmit={recordPayment} className="rounded-2xl border border-line bg-panel p-5"><h2 className="font-semibold">Record bank / offline payment</h2><p className="mt-1 text-xs text-ink-4">A human assertion, stored separately from provider-verified money.</p><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs text-ink-3">Amount (₹)<input name="amount" type="number" min="0.01" step="0.01" required className="mt-1 w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm" /></label><label className="text-xs text-ink-3">Method<select name="method" className="mt-1 w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm"><option value="bank_transfer">Bank transfer</option><option value="upi">UPI</option><option value="cheque">Cheque</option><option value="cash">Cash</option><option value="adjustment">Credit / adjustment</option></select></label><label className="col-span-2 text-xs text-ink-3">Reference<input name="reference" required className="mt-1 w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm" placeholder="UTR, cheque, or credit-note number" /></label><label className="text-xs text-ink-3">Received on<input name="received_on" type="date" required className="mt-1 w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm" /></label><label className="text-xs text-ink-3">Note<input name="note" className="mt-1 w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm" /></label></div><button className="mt-3 w-full rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white">Record payment</button></form>
        <div><h2 className="mb-3 text-sm font-semibold">Reminders sent ({data.reminders.length} of 3)</h2><div className="space-y-3">{data.reminders.map((reminder) => <article key={reminder.tier} className="rounded-xl border border-line bg-panel"><div className="flex flex-wrap items-center gap-2 border-b border-line px-4 py-2.5"><span className="text-sm font-medium">Tier {reminder.tier}</span><span className="rounded bg-panel-2 px-2 py-0.5 text-[11px] text-ink-2">{reminder.tone}</span><span className="rounded bg-panel-2 px-2 py-0.5 font-mono text-[10px] text-ink-3">{reminder.generated_by}</span></div><div className="px-4 py-3"><p className="text-sm font-medium">{reminder.subject}</p><p className="mt-2 whitespace-pre-wrap text-[13px] leading-relaxed text-ink-3">{reminder.body}</p></div></article>)}{!data.reminders.length ? <p className="rounded-xl border border-line bg-panel px-4 py-6 text-center text-sm text-ink-3">No reminders sent yet.</p> : null}</div></div>
        {data.promises.length ? <div><h2 className="mb-3 text-sm font-semibold">Promises</h2><div className="space-y-2">{data.promises.map((promise) => <article key={promise.id} className="rounded-lg border border-line bg-panel px-4 py-3"><div className="flex items-center justify-between gap-3"><span className="text-sm">by {promise.promised_date}</span><span className="rounded-full border border-line px-2 py-0.5 text-[10px] capitalize text-ink-2">{promise.status}</span></div><p className="mt-1.5 text-xs italic text-ink-3">“{promise.excerpt}”</p><p className="mt-1 text-[11px] text-ink-4">{promise.amount_display} · confidence {(promise.confidence * 100).toFixed(0)}%</p></article>)}</div></div> : null}
        {data.external_payments.length ? <section className="rounded-2xl border border-line bg-panel p-5"><h2 className="font-semibold">Recorded payments</h2><div className="mt-3 space-y-3">{data.external_payments.map((payment) => <div key={payment.id} className="text-sm"><div className="flex justify-between"><span>{payment.method_label || "External"}</span><strong>{payment.amount_display}</strong></div><p className="text-xs text-ink-4">{payment.reference} · {payment.received_on}{payment.reversed_at ? " · reversed" : ""}</p></div>)}</div></section> : null}
        <button onClick={escalate} className="w-full rounded-lg border border-line px-4 py-2 text-sm">Escalate to human review</button>
      </aside>
    </div>
  </div>;
}
