import Link from "next/link";

export const metadata = { title: "Privacy Policy — Vasooli", description: "How Vasooli collects, uses, secures, and retains personal and business data." };

const SECTIONS = [
  ["1. Scope", "This Privacy Policy explains how Vasooli processes information when you visit our website, create an account, use a merchant workspace, contact support, or interact with receivables communications sent through our service. A merchant using Vasooli controls the customer and invoice data it uploads; Vasooli processes that data on the merchant’s instructions."],
  ["2. Information we collect", "We collect account and profile details, business and billing information, workspace membership, invoices, customer contact details, promises, disputes, message content and delivery events, payment references, integration configuration, device and request information, operational logs, and support communications. We do not ask you to provide full payment-card details to Vasooli."],
  ["3. How we use information", "We use information to authenticate users, operate and secure workspaces, synchronize receivables, apply communication policy, deliver and receive messages, reconcile payments, provide support, prevent abuse, improve reliability, comply with law, and create an attributable record of automated and human actions."],
  ["4. Legal bases and merchant responsibility", "Where applicable, processing is based on contract, legitimate interests, consent, and legal obligations. Merchants are responsible for establishing a lawful basis to upload customer data and contact recipients. Vasooli does not sell personal information or use customer receivables data for third-party advertising."],
  ["5. AI-assisted processing", "AI may help classify replies and draft language. Authoritative invoice facts are supplied and validated by the application. Model output cannot itself send communication, change a balance, or mark an invoice paid. We configure providers to receive only information needed for the requested task."],
  ["6. Service providers and transfers", "Infrastructure, email delivery, AI, ERP, analytics, support, and payment providers may process limited data on our behalf under contractual safeguards. Data may be processed outside your region where our providers operate, subject to applicable transfer mechanisms."],
  ["7. Security", "We use tenant-scoped access, role permissions, encrypted credentials, signed webhooks, secure session cookies, rate limits, audit records, transport encryption, and operational monitoring. No service can guarantee absolute security. Report a suspected vulnerability to security@vasooli.space."],
  ["8. Retention", "Account, workspace, invoice, message, payment, and audit data are retained while needed to provide the service and for legitimate security, financial, dispute, and legal purposes. Deletion requests are applied according to configured retention rules; limited records may remain where law or audit integrity requires them."],
  ["9. Your choices and rights", "Depending on your location, you may request access, correction, deletion, restriction, portability, or objection. Workspace administrators can request exports and deletion for merchant-controlled data. We may verify identity and authority before acting on a request."],
  ["10. Cookies", "Vasooli uses essential cookies for authentication, session security, and request protection. We do not use cross-site advertising cookies. Browser storage may retain non-sensitive preferences and the selected workspace."],
  ["11. Children", "Vasooli is a business service and is not intended for anyone under 18. We do not knowingly collect children’s personal information."],
  ["12. Changes and contact", "We may update this policy as the service or law changes. Material changes will be communicated through the service or account email. For privacy questions or requests, email privacy@vasooli.space."],
];

export default function PrivacyPage() {
  return <main className="legal-page"><header><p className="public-eyebrow">Legal · Privacy</p><h1>Privacy Policy</h1><p>Effective 31 August 2026 · Last updated 31 August 2026</p><div className="legal-summary">Vasooli is built to recover receivables without losing control of the data behind them. We collect only what is needed to operate, secure, and evidence the service.</div></header><div className="legal-layout"><aside aria-label="Policy navigation"><strong>On this page</strong>{SECTIONS.map(([title]) => <a key={title} href={`#section-${title.split(".")[0]}`}>{title}</a>)}</aside><article>{SECTIONS.map(([title, body]) => <section key={title} id={`section-${title.split(".")[0]}`}><h2>{title}</h2><p>{body}</p></section>)}<section><h2>Related documents</h2><p>Read our <Link href="/terms">Terms of Service</Link> and <Link href="/dpa">Data Processing Addendum</Link> for contractual terms that apply to the service.</p></section></article></div></main>;
}
