import Link from "next/link";

export const metadata = { title: "Terms of Service — Vasooli", description: "The terms governing access to and use of the Vasooli receivables recovery platform." };

const SECTIONS = [
  ["1. Agreement and eligibility", "By creating an account or using Vasooli, you agree to these Terms on behalf of yourself and the organization you identify. You must be at least 18, able to form a binding contract, and authorized to act for that organization."],
  ["2. The service", "Vasooli provides receivables workflow, communication, reconciliation, and audit software. It is not a bank, payment aggregator, law firm, debt purchaser, credit bureau, or accounting system of record, and it does not provide legal, tax, or financial advice."],
  ["3. Accounts and security", "You must provide accurate account information, keep credentials confidential, use individual accounts, and promptly report suspected compromise. You are responsible for activity under your workspace except to the extent caused by Vasooli’s breach of these Terms."],
  ["4. Your data and instructions", "You retain ownership of data you submit. You grant Vasooli the limited rights needed to host, process, transmit, and display it to provide and secure the service. You must have lawful authority to upload customer and invoice data, connect providers, and instruct communications."],
  ["5. Collection communications", "You control recipient eligibility, sender identity, policy, tone, schedules, and escalation. You must honor applicable collection, privacy, anti-spam, consumer-protection, quiet-hour, and opt-out requirements. You may not use Vasooli to harass, threaten, deceive, or unlawfully contact anyone."],
  ["6. Financial records and automation", "Provider events and authorized operator entries update the Vasooli ledger. You must review exceptions, disputes, refunds, chargebacks, partial payments, and source-system changes. AI output and customer statements do not independently establish payment or change a balance."],
  ["7. Fees, trials, and taxes", "Paid subscriptions renew at the interval shown at checkout until cancelled. Trials may be limited to one per organization. Prices exclude applicable taxes. You authorize our payment provider to charge the selected plan and agree to keep billing details current."],
  ["8. Cancellation and refunds", "You may cancel through workspace billing or by contacting support. Cancellation takes effect at the end of the current paid period unless law requires otherwise. Fees are non-refundable except where required by law or expressly stated at purchase."],
  ["9. Acceptable use", "You may not misuse the service, probe or bypass security, access another tenant, upload malicious code, overload infrastructure, reverse engineer protected components, resell access without permission, violate third-party rights, or use data you have no right to process."],
  ["10. Confidentiality and data protection", "Each party must protect the other’s non-public business information and use it only for the relationship. Our Privacy Policy explains our handling of account data, and the Data Processing Addendum applies where Vasooli processes personal data for a merchant."],
  ["11. Availability and changes", "We work to keep Vasooli reliable but do not guarantee uninterrupted operation. Maintenance, provider failures, emergencies, or legal requirements may affect availability. We may improve or change features while preserving the material purpose of a paid plan."],
  ["12. Suspension and termination", "We may restrict access for non-payment, unlawful use, security risk, material breach, or legal requirement. You may stop using the service at any time. On termination, access and data handling follow the applicable billing, export, and retention terms."],
  ["13. Disclaimers", "To the extent permitted by law, the service is provided as available. We disclaim implied warranties of merchantability, fitness for a particular purpose, and non-infringement. You remain responsible for collection decisions and the accuracy of source financial records."],
  ["14. Limitation of liability", "To the extent permitted by law, neither party is liable for indirect, incidental, special, punitive, or consequential loss. Vasooli’s aggregate liability arising from the service will not exceed fees paid for the affected service during the twelve months before the event giving rise to the claim."],
  ["15. Governing terms and contact", "If part of these Terms is unenforceable, the remainder continues. Failure to enforce a term is not a waiver. These Terms, the applicable order, Privacy Policy, and Data Processing Addendum form the agreement. Questions and legal notices may be sent to legal@vasooli.space."],
];

export default function TermsPage() {
  return <main className="legal-page"><header><p className="public-eyebrow">Legal · Terms</p><h1>Terms of Service</h1><p>Effective 31 August 2026 · Last updated 31 August 2026</p><div className="legal-summary">These terms define the responsibilities behind controlled receivables recovery—what Vasooli operates, what your organization controls, and where financial authority remains.</div></header><div className="legal-layout"><aside aria-label="Terms navigation"><strong>On this page</strong>{SECTIONS.map(([title]) => <a key={title} href={`#section-${title.split(".")[0]}`}>{title}</a>)}</aside><article>{SECTIONS.map(([title, body]) => <section key={title} id={`section-${title.split(".")[0]}`}><h2>{title}</h2><p>{body}</p></section>)}<section><h2>Related documents</h2><p>Review our <Link href="/privacy">Privacy Policy</Link> and <Link href="/dpa">Data Processing Addendum</Link> before using a live workspace.</p></section></article></div></main>;
}
