"""add demo clock

Single-row table holding how far ahead of real time the simulated clock runs, so the
3/10/21-day cadence can be walked in a review instead of over three weeks. Additive:
new table only, and its downgrade is a clean drop.

The `id = 1` check constraint is the load-bearing part — it makes a second row
impossible, so there can never be an offset row that nobody is reading.

Revision ID: 1b0e325f394d
Revises: c82e9f7a4b10
Create Date: 2026-08-30 01:37:18.902962

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.AutoString in autogenerate

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b0e325f394d"
down_revision: str | Sequence[str] | None = "c82e9f7a4b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demo_clock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offset_days", sa.Integer(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("id = 1", name="ck_demo_clock_singleton"),
        sa.CheckConstraint(
            "offset_days >= 0 AND offset_days <= 3650", name="ck_demo_clock_offset_range"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("demo_clock")
    # ### end Alembic commands ###
