"""add payment link closure tracking

Revision ID: 28048a29736f
Revises: 5c3440022ce5
Create Date: 2026-08-23 20:34:21.871126

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.AutoString in autogenerate

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28048a29736f"
down_revision: str | Sequence[str] | None = "5c3440022ce5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; dropped immediately after so the
    # column definition keeps matching the model and `alembic check` stays useful.
    op.add_column(
        "payment_links",
        sa.Column("closure_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("payment_links", "closure_attempts", server_default=None)
    op.add_column(
        "payment_links",
        sa.Column("closure_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "payment_links",
        sa.Column("next_closure_retry_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_links", "next_closure_retry_at")
    op.drop_column("payment_links", "closure_error")
    op.drop_column("payment_links", "closure_attempts")
    # ### end Alembic commands ###
