"""add dispute cases

Adds the human-review case a disputed invoice gets. New table only — no existing
column changes — so the migration is additive and its downgrade is a clean drop.

The partial unique index is the load-bearing part: `status = 'open'` means at most
one open case per invoice while resolved ones accumulate as history. That is what
makes replaying the same customer reply idempotent at the database level rather than
only in application code.

Revision ID: 2f47bba4f219
Revises: 52bdd51e0631
Create Date: 2026-08-24 19:52:53.685515

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.AutoString in autogenerate
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f47bba4f219"
down_revision: str | Sequence[str] | None = "52bdd51e0631"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispute_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_reply_number", sa.Integer(), nullable=False),
        sa.Column("detected_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ai_degraded", sa.Boolean(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resolution_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recovery_resumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_dispute_cases_confidence_range"
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dispute_cases_invoice_id"), "dispute_cases", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_dispute_cases_source_fingerprint"),
        "dispute_cases",
        ["source_fingerprint"],
        unique=False,
    )
    op.create_index(op.f("ix_dispute_cases_status"), "dispute_cases", ["status"], unique=False)
    op.create_index(
        "uq_dispute_cases_one_open_per_invoice",
        "dispute_cases",
        ["invoice_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_dispute_cases_one_open_per_invoice",
        table_name="dispute_cases",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_dispute_cases_status"), table_name="dispute_cases")
    op.drop_index(op.f("ix_dispute_cases_source_fingerprint"), table_name="dispute_cases")
    op.drop_index(op.f("ix_dispute_cases_invoice_id"), table_name="dispute_cases")
    op.drop_table("dispute_cases")
    # ### end Alembic commands ###
