"""add webhook event retry state

Revision ID: 38d15bf18d3f
Revises: 889b9428871f
Create Date: 2026-08-23 20:40:40.707524

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.AutoString in autogenerate

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38d15bf18d3f"
down_revision: str | Sequence[str] | None = "28048a29736f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reconciliation_events",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("reconciliation_events", sa.Column("attempts", sa.Integer(), nullable=False))
    op.add_column(
        "reconciliation_events",
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "reconciliation_events",
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_reconciliation_events_status"), "reconciliation_events", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reconciliation_events_status"), table_name="reconciliation_events")
    op.drop_column("reconciliation_events", "next_retry_at")
    op.drop_column("reconciliation_events", "last_attempt_at")
    op.drop_column("reconciliation_events", "attempts")
    op.drop_column("reconciliation_events", "status")
    # ### end Alembic commands ###
