"""baseline schema

Revision ID: 44ea088abeee
Revises:
Create Date: 2026-08-22 14:15:32.751543

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44ea088abeee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reply_to_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("razorpay_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_invoices", sa.Integer(), nullable=False),
        sa.Column("invoices_paid_late", sa.Integer(), nullable=False),
        sa.Column("invoices_defaulted", sa.Integer(), nullable=False),
        sa.Column("broken_promises", sa.Integer(), nullable=False),
        sa.Column("avg_invoice_paise", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("broken_promises >= 0", name="ck_customers_broken_non_negative"),
        sa.CheckConstraint(
            "invoices_defaulted >= 0 AND invoices_defaulted <= total_invoices",
            name="ck_customers_defaulted_within_total",
        ),
        sa.CheckConstraint(
            "invoices_paid_late >= 0 AND invoices_paid_late <= total_invoices",
            name="ck_customers_late_within_total",
        ),
        sa.CheckConstraint("total_invoices >= 0", name="ck_customers_total_non_negative"),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=False)
    op.create_index(op.f("ix_customers_merchant_id"), "customers", ["merchant_id"], unique=False)
    op.create_index(
        op.f("ix_customers_razorpay_customer_id"),
        "customers",
        ["razorpay_customer_id"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("amount_paid_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms_days", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason_category", sa.String(), nullable=True),
        sa.Column("reason_explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reason_confidence", sa.Float(), nullable=True),
        sa.Column("reason_diagnosed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason_llm_disagreed", sa.Boolean(), nullable=False),
        sa.Column("reminders_sent", sa.Integer(), nullable=False),
        sa.Column("current_tier", sa.Integer(), nullable=False),
        sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_to_human_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("has_prior_dispute_note", sa.Boolean(), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount_paid_paise >= 0", name="ck_invoices_paid_non_negative"),
        sa.CheckConstraint("amount_paise > 0", name="ck_invoices_amount_positive"),
        sa.CheckConstraint(
            "current_tier >= 0 AND current_tier <= 3", name="ck_invoices_tier_range"
        ),
        sa.CheckConstraint("due_at >= issued_at", name="ck_invoices_due_after_issue"),
        sa.CheckConstraint(
            "reminders_sent >= 0 AND reminders_sent <= 3", name="ck_invoices_reminder_cap"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_customer_id"), "invoices", ["customer_id"], unique=False)
    op.create_index(op.f("ix_invoices_due_at"), "invoices", ["due_at"], unique=False)
    op.create_index(op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=True)
    op.create_index(op.f("ix_invoices_merchant_id"), "invoices", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor"), "audit_logs", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_invoice_id"), "audit_logs", ["invoice_id"], unique=False)
    op.create_table(
        "promises",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("promised_date", sa.Date(), nullable=False),
        sa.Column("promised_amount_paise", sa.BigInteger(), nullable=True),
        sa.Column("source_message_excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("tier_at_pause", sa.Integer(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "extraction_confidence >= 0 AND extraction_confidence <= 1",
            name="ck_promises_confidence_range",
        ),
        sa.CheckConstraint(
            "promised_amount_paise IS NULL OR promised_amount_paise > 0",
            name="ck_promises_amount_positive",
        ),
        sa.CheckConstraint(
            "tier_at_pause >= 0 AND tier_at_pause <= 3", name="ck_promises_tier_range"
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promises_invoice_id"), "promises", ["invoice_id"], unique=False)
    op.create_index(op.f("ix_promises_status"), "promises", ["status"], unique=False)
    op.create_index(
        "uq_promises_one_active_per_invoice",
        "promises",
        ["invoice_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "reconciliation_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("matched_invoice_id", sa.UUID(), nullable=True),
        sa.Column("match_strategy", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount_paise", sa.BigInteger(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_events_event_type"),
        "reconciliation_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_events_matched_invoice_id"),
        "reconciliation_events",
        ["matched_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_events_provider_event_id"),
        "reconciliation_events",
        ["provider_event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_reconciliation_events_received_at"),
        "reconciliation_events",
        ["received_at"],
        unique=False,
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("tone", sa.String(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider_message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("policy_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("llm_degraded", sa.Boolean(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("send_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("tier >= 1 AND tier <= 3", name="ck_reminders_tier_range"),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id", "tier", name="uq_reminders_invoice_tier"),
    )
    op.create_index(op.f("ix_reminders_invoice_id"), "reminders", ["invoice_id"], unique=False)
    op.create_table(
        "virtual_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("razorpay_va_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("razorpay_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount_expected_paise", sa.BigInteger(), nullable=False),
        sa.Column("amount_paid_paise", sa.BigInteger(), nullable=False),
        sa.Column("bank_account_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bank_account_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bank_ifsc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provisioned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount_expected_paise > 0", name="ck_va_expected_positive"),
        sa.CheckConstraint("amount_paid_paise >= 0", name="ck_va_paid_non_negative"),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_virtual_accounts_invoice_id"), "virtual_accounts", ["invoice_id"], unique=True
    )
    op.create_index(
        op.f("ix_virtual_accounts_razorpay_va_id"),
        "virtual_accounts",
        ["razorpay_va_id"],
        unique=True,
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # audit_logs is append-only (Doc §3 Stage 6).
    #
    # Enforced with a trigger rather than REVOKE UPDATE/DELETE, because table
    # privileges do not apply to superusers or to the table's owner — which is
    # exactly who the app connects as in local development and on Railway. A
    # trigger raises for every role, so the guarantee is the same everywhere.
    #
    # The demo shows this log as evidence; a log that could be quietly edited
    # is not evidence.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION vasooli_audit_logs_append_only()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_logs is append-only: % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION vasooli_audit_logs_append_only();
        """
    )


def downgrade() -> None:
    # The trigger must go before the table it guards, or the DROP TABLE itself
    # would be blocked in some Postgres configurations.
    op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs;")
    op.execute("DROP FUNCTION IF EXISTS vasooli_audit_logs_append_only();")

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_virtual_accounts_razorpay_va_id"), table_name="virtual_accounts")
    op.drop_index(op.f("ix_virtual_accounts_invoice_id"), table_name="virtual_accounts")
    op.drop_table("virtual_accounts")
    op.drop_index(op.f("ix_reminders_invoice_id"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_reconciliation_events_received_at"), table_name="reconciliation_events")
    op.drop_index(
        op.f("ix_reconciliation_events_provider_event_id"), table_name="reconciliation_events"
    )
    op.drop_index(
        op.f("ix_reconciliation_events_matched_invoice_id"), table_name="reconciliation_events"
    )
    op.drop_index(op.f("ix_reconciliation_events_event_type"), table_name="reconciliation_events")
    op.drop_table("reconciliation_events")
    op.drop_index(
        "uq_promises_one_active_per_invoice",
        table_name="promises",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_promises_status"), table_name="promises")
    op.drop_index(op.f("ix_promises_invoice_id"), table_name="promises")
    op.drop_table("promises")
    op.drop_index(op.f("ix_audit_logs_invoice_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_merchant_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_due_at"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_customer_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_customers_razorpay_customer_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_merchant_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    op.drop_table("merchants")
    # ### end Alembic commands ###
