"""add invoice reply history

Revision ID: 52bdd51e0631
Revises: 5b80717caca1
Create Date: 2026-08-23 20:50:59.926186

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.AutoString in autogenerate

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52bdd51e0631"
down_revision: str | Sequence[str] | None = "5b80717caca1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("reply_count", sa.Integer(), nullable=False))
    op.add_column("invoices", sa.Column("last_reply_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "invoices",
        sa.Column("last_reply_excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "last_reply_excerpt")
    op.drop_column("invoices", "last_reply_at")
    op.drop_column("invoices", "reply_count")
    # ### end Alembic commands ###
