"""add invoice reply history

Revision ID: 5b80717caca1
Revises: 38d15bf18d3f
Create Date: 2026-08-23 20:50:30.104626

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5b80717caca1"
down_revision: str | Sequence[str] | None = "38d15bf18d3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
