"""add reminder delivery attempt tracking

Revision ID: 5c3440022ce5
Revises: d8a9d537495f
Create Date: 2026-08-23 20:27:06.021525

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c3440022ce5"
down_revision: str | Sequence[str] | None = "d8a9d537495f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills rows that already exist; without it this ALTER fails
    # on any database that has reminders in it.
    op.add_column(
        "reminders",
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # The default existed only to backfill; dropping it keeps the column definition
    # matching the model, so `alembic check` stays clean and future drift is real.
    op.alter_column("reminders", "attempt_count", server_default=None)
    op.add_column(
        "reminders", sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "reminders", sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reminders", "next_retry_at")
    op.drop_column("reminders", "last_attempt_at")
    op.drop_column("reminders", "attempt_count")
    # ### end Alembic commands ###
