"""replace virtual accounts with payment links

Revision ID: d8a9d537495f
Revises: 44ea088abeee
Create Date: 2026-08-22 17:43:58.286397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.AutoString in autogenerate
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8a9d537495f'
down_revision: Union[str, Sequence[str], None] = '44ea088abeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_expected_paise', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid_paise', sa.BigInteger(), nullable=False),
    sa.Column('accept_partial', sa.Boolean(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_expected_paise > 0', name='ck_payment_links_expected_positive'),
    sa.CheckConstraint('amount_paid_paise >= 0', name='ck_payment_links_paid_non_negative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_invoice_id'), 'payment_links', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_payment_links_razorpay_payment_link_id'), 'payment_links', ['razorpay_payment_link_id'], unique=True)
    op.create_index(op.f('ix_payment_links_reference_id'), 'payment_links', ['reference_id'], unique=True)
    op.drop_index(op.f('ix_virtual_accounts_invoice_id'), table_name='virtual_accounts')
    op.drop_index(op.f('ix_virtual_accounts_razorpay_va_id'), table_name='virtual_accounts')
    op.drop_table('virtual_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('razorpay_va_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('razorpay_customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount_expected_paise', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('amount_paid_paise', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bank_account_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_ifsc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('provisioned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('amount_expected_paise > 0', name=op.f('ck_va_expected_positive')),
    sa.CheckConstraint('amount_paid_paise >= 0', name=op.f('ck_va_paid_non_negative')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('virtual_accounts_invoice_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('virtual_accounts_pkey'))
    )
    op.create_index(op.f('ix_virtual_accounts_razorpay_va_id'), 'virtual_accounts', ['razorpay_va_id'], unique=True)
    op.create_index(op.f('ix_virtual_accounts_invoice_id'), 'virtual_accounts', ['invoice_id'], unique=True)
    op.drop_index(op.f('ix_payment_links_reference_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_razorpay_payment_link_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_invoice_id'), table_name='payment_links')
    op.drop_table('payment_links')
    # ### end Alembic commands ###
